In [40]:
# merging the rainfall data(maharain_district_rainfall_1998_2022.csv) and crop(master_crop_data_clean.csv)

In [41]:
import pandas as pd

In [44]:
df_rain=pd.read_csv("data/maharain_district_rainfall_1998_2022.csv")
df_crop=pd.read_csv("data/master_crop_data_clean.csv")

In [43]:
df_rain.head(3)

,year,division_code,division_name,row_order,location_name,june_normal_rainfall,june_actual_rainfall,june_percent_to_normal,july_normal_rainfall,july_actual_rainfall,july_percent_to_normal,august_normal_rainfall,august_actual_rainfall,august_percent_to_normal,september_normal_rainfall,september_actual_rainfall,september_percent_to_normal
0,1998,5,Amravati,1,buldhana,139.3,122.1,87.7,192.2,261.4,136.0,207.4,216.4,104.3,120.5,234.5,194.6
1,1998,5,Amravati,2,akola,136.9,239.1,174.7,223.2,340.8,152.7,215.5,212.1,98.4,118.1,163.0,138.0
2,1998,5,Amravati,3,washim,166.4,96.6,58.1,243.6,210.0,86.2,236.1,217.0,91.9,142.9,386.3,270.3

In [45]:
df_crop.head(3)

,District,Year,Crop,Season,Area,Production,Yield,Yield_Lag1,Yield_Lag2,Yield_3yr_Avg,Yield_3yr_Std
0,Ahilyanagar,1997,Arhar_Tur,Kharif,17600.0,6300.0,0.357955,0.357955,0.357955,0.357955,0.0
1,Ahilyanagar,1997,Bajra,Kharif,274100.0,152800.0,0.557461,0.557461,0.557461,0.557461,0.0
2,Ahilyanagar,1997,Gram,Kharif,40800.0,18600.0,0.455882,0.455882,0.455882,0.455882,0.0

In [46]:
df_rain.columns

Index(['year', 'division_code', 'division_name', 'row_order', 'location_name',
       'june_normal_rainfall', 'june_actual_rainfall',
       'june_percent_to_normal', 'july_normal_rainfall',
       'july_actual_rainfall', 'july_percent_to_normal',
       'august_normal_rainfall', 'august_actual_rainfall',
       'august_percent_to_normal', 'september_normal_rainfall',
       'september_actual_rainfall', 'september_percent_to_normal'],
      dtype='str')

In [47]:
df_crop.columns

Index(['District', 'Year', 'Crop', 'Season', 'Area', 'Production', 'Yield',
       'Yield_Lag1', 'Yield_Lag2', 'Yield_3yr_Avg', 'Yield_3yr_Std'],
      dtype='str')

In [48]:
df_crop["District"].unique()

<StringArray>
[              'Ahilyanagar',                     'Akola',
                  'Amravati',                      'Beed',
                  'Bhandara',                  'Buldhana',
                'Chandrapur', 'Chhatrapati Sambhajinagar',
                 'Dharashiv',                     'Dhule',
                'Gadchiroli',                    'Gondia',
                   'Hingoli',                   'Jalgaon',
                     'Jalna',                  'Kolhapur',
                     'Latur',                    'Mumbai',
           'Mumbai suburban',                    'Nagpur',
                    'Nanded',                 'Nandurbar',
                    'Nashik',                   'Palghar',
                  'Parbhani',                      'Pune',
                    'Raigad',                 'Ratnagiri',
                    'Sangli',                    'Satara',
                'Sindhudurg',                   'Solapur',
                     'Thane',                    'Wardha',
                    'Washim',                  'Yavatmal']
Length: 36, dtype: str

In [49]:
df_rain.nunique()

year                            25
division_code                    6
division_name                    6
row_order                        8
location_name                   34
june_normal_rainfall            34
june_actual_rainfall           765
june_percent_to_normal         663
july_normal_rainfall            34
july_actual_rainfall           801
july_percent_to_normal         663
august_normal_rainfall          34
august_actual_rainfall         788
august_percent_to_normal       633
september_normal_rainfall       34
september_actual_rainfall      757
september_percent_to_normal    684
dtype: int64

In [50]:
df_rain["location_name"].unique()

<StringArray>
[                 'Buldhana',                     'Akola',
                    'Washim',                  'Amravati',
                  'Yavatmal', 'Chhatrapati Sambhajinagar',
                     'Jalna',                      'Beed',
                     'Latur',                 'Dharashiv',
                    'Nanded',                 'Parabhani',
                   'Hingoli',                     'Thane',
                   'Raigadh',                 'Ratnagiri',
                'Sindhudurg',                   'Palghar',
                    'Wardha',                    'Nagpur',
                  'Bhandara',                    'Gondia',
                'Chandrapur',                'Gadchiroli',
                    'Nashik',                     'Dhule',
                 'Nandurbar',                   'Jalgaon',
               'Ahilyanagar',                      'Pune',
                   'Solapur',                    'Satara',
                    'Sangli',                  'Kolhapur']
Length: 34, dtype: str

In [51]:
# Makes sure bothe the columns(district and location name) have same name cases i.e., lower
def clean_text(col):
    return col.str.lower().str.strip()

df_crop["District"] = clean_text(df_crop["District"])
df_rain["location_name"] = clean_text(df_rain["location_name"])

In [52]:
df_crop["District"].unique()

<StringArray>
[              'ahilyanagar',                     'akola',
                  'amravati',                      'beed',
                  'bhandara',                  'buldhana',
                'chandrapur', 'chhatrapati sambhajinagar',
                 'dharashiv',                     'dhule',
                'gadchiroli',                    'gondia',
                   'hingoli',                   'jalgaon',
                     'jalna',                  'kolhapur',
                     'latur',                    'mumbai',
           'mumbai suburban',                    'nagpur',
                    'nanded',                 'nandurbar',
                    'nashik',                   'palghar',
                  'parbhani',                      'pune',
                    'raigad',                 'ratnagiri',
                    'sangli',                    'satara',
                'sindhudurg',                   'solapur',
                     'thane',                    'wardha',
                    'washim',                  'yavatmal']
Length: 36, dtype: str

In [53]:
df_rain["location_name"].unique()

<StringArray>
[                 'buldhana',                     'akola',
                    'washim',                  'amravati',
                  'yavatmal', 'chhatrapati sambhajinagar',
                     'jalna',                      'beed',
                     'latur',                 'dharashiv',
                    'nanded',                 'parabhani',
                   'hingoli',                     'thane',
                   'raigadh',                 'ratnagiri',
                'sindhudurg',                   'palghar',
                    'wardha',                    'nagpur',
                  'bhandara',                    'gondia',
                'chandrapur',                'gadchiroli',
                    'nashik',                     'dhule',
                 'nandurbar',                   'jalgaon',
               'ahilyanagar',                      'pune',
                   'solapur',                    'satara',
                    'sangli',                  'kolhapur']
Length: 34, dtype: str

In [54]:
set(df_crop["District"]) - set(df_rain["location_name"])

{'mumbai', 'mumbai suburban', 'parbhani', 'raigad'}

In [55]:
# THIS ERROR OCCURED AS BOTH THE DATASET HAVE NAME MISMATCH:
#"raigad": "raigadh",
#"parbhani": "parabhani"

In [56]:
# NAME MISMATCH FIX
mapping_fix = {
    "raigadh": "raigad",
    "parabhani": "parbhani"
}

df_rain["location_name"] = df_rain["location_name"].replace(mapping_fix)

In [57]:
df_rain["location_name"].unique()

<StringArray>
[                 'buldhana',                     'akola',
                    'washim',                  'amravati',
                  'yavatmal', 'chhatrapati sambhajinagar',
                     'jalna',                      'beed',
                     'latur',                 'dharashiv',
                    'nanded',                  'parbhani',
                   'hingoli',                     'thane',
                    'raigad',                 'ratnagiri',
                'sindhudurg',                   'palghar',
                    'wardha',                    'nagpur',
                  'bhandara',                    'gondia',
                'chandrapur',                'gadchiroli',
                    'nashik',                     'dhule',
                 'nandurbar',                   'jalgaon',
               'ahilyanagar',                      'pune',
                   'solapur',                    'satara',
                    'sangli',                  'kolhapur']
Length: 34, dtype: str

In [58]:
df_crop["District"].unique()

<StringArray>
[              'ahilyanagar',                     'akola',
                  'amravati',                      'beed',
                  'bhandara',                  'buldhana',
                'chandrapur', 'chhatrapati sambhajinagar',
                 'dharashiv',                     'dhule',
                'gadchiroli',                    'gondia',
                   'hingoli',                   'jalgaon',
                     'jalna',                  'kolhapur',
                     'latur',                    'mumbai',
           'mumbai suburban',                    'nagpur',
                    'nanded',                 'nandurbar',
                    'nashik',                   'palghar',
                  'parbhani',                      'pune',
                    'raigad',                 'ratnagiri',
                    'sangli',                    'satara',
                'sindhudurg',                   'solapur',
                     'thane',                    'wardha',
                    'washim',                  'yavatmal']
Length: 36, dtype: str

In [59]:
set(df_crop["District"]) - set(df_rain["location_name"])

{'mumbai', 'mumbai suburban'}

In [60]:
# NOW THE NAME MISMATCH HAS BEEN RESOLVED AND ONLY THE MISSING DATASET OF MUMBAI AND MUM. SUBS ARE IN DISJOINT

In [61]:
df=pd.merge(
    df_crop,
    df_rain, 
    left_on=["Year", "District"],
    right_on=["year", "location_name"],
    how="inner"
)

In [62]:
df.columns

Index(['District', 'Year', 'Crop', 'Season', 'Area', 'Production', 'Yield',
       'Yield_Lag1', 'Yield_Lag2', 'Yield_3yr_Avg', 'Yield_3yr_Std', 'year',
       'division_code', 'division_name', 'row_order', 'location_name',
       'june_normal_rainfall', 'june_actual_rainfall',
       'june_percent_to_normal', 'july_normal_rainfall',
       'july_actual_rainfall', 'july_percent_to_normal',
       'august_normal_rainfall', 'august_actual_rainfall',
       'august_percent_to_normal', 'september_normal_rainfall',
       'september_actual_rainfall', 'september_percent_to_normal'],
      dtype='str')

In [63]:
df['District'].unique()

<StringArray>
[              'ahilyanagar',                     'akola',
                  'amravati',                      'beed',
                  'bhandara',                  'buldhana',
                'chandrapur', 'chhatrapati sambhajinagar',
                 'dharashiv',                     'dhule',
                'gadchiroli',                    'gondia',
                   'hingoli',                   'jalgaon',
                     'jalna',                  'kolhapur',
                     'latur',                    'nagpur',
                    'nanded',                 'nandurbar',
                    'nashik',                   'palghar',
                  'parbhani',                      'pune',
                    'raigad',                 'ratnagiri',
                    'sangli',                    'satara',
                'sindhudurg',                   'solapur',
                     'thane',                    'wardha',
                    'washim',                  'yavatmal']
Length: 34, dtype: str

In [64]:
df[["District", "location_name"]].sample(5)

         District location_name
9386     kolhapur      kolhapur
18200      wardha        wardha
7645      jalgaon       jalgaon
11260      nanded        nanded
6571   gadchiroli    gadchiroli

In [65]:
df.shape

(19439, 28)

In [66]:
df.isna().sum()

District                       0
Year                           0
Crop                           0
Season                         0
Area                           0
Production                     0
Yield                          0
Yield_Lag1                     0
Yield_Lag2                     0
Yield_3yr_Avg                  0
Yield_3yr_Std                  0
year                           0
division_code                  0
division_name                  0
row_order                      0
location_name                  0
june_normal_rainfall           0
june_actual_rainfall           0
june_percent_to_normal         0
july_normal_rainfall           0
july_actual_rainfall           0
july_percent_to_normal         0
august_normal_rainfall         0
august_actual_rainfall         0
august_percent_to_normal       0
september_normal_rainfall      0
september_actual_rainfall      0
september_percent_to_normal    0
dtype: int64

In [67]:
df.columns

Index(['District', 'Year', 'Crop', 'Season', 'Area', 'Production', 'Yield',
       'Yield_Lag1', 'Yield_Lag2', 'Yield_3yr_Avg', 'Yield_3yr_Std', 'year',
       'division_code', 'division_name', 'row_order', 'location_name',
       'june_normal_rainfall', 'june_actual_rainfall',
       'june_percent_to_normal', 'july_normal_rainfall',
       'july_actual_rainfall', 'july_percent_to_normal',
       'august_normal_rainfall', 'august_actual_rainfall',
       'august_percent_to_normal', 'september_normal_rainfall',
       'september_actual_rainfall', 'september_percent_to_normal'],
      dtype='str')

In [68]:
df = df.drop(columns=[
    "year",
    "location_name",
    "division_code",
    "division_name",
    "row_order"
])

In [69]:
df.columns

Index(['District', 'Year', 'Crop', 'Season', 'Area', 'Production', 'Yield',
       'Yield_Lag1', 'Yield_Lag2', 'Yield_3yr_Avg', 'Yield_3yr_Std',
       'june_normal_rainfall', 'june_actual_rainfall',
       'june_percent_to_normal', 'july_normal_rainfall',
       'july_actual_rainfall', 'july_percent_to_normal',
       'august_normal_rainfall', 'august_actual_rainfall',
       'august_percent_to_normal', 'september_normal_rainfall',
       'september_actual_rainfall', 'september_percent_to_normal'],
      dtype='str')

In [70]:
df.head(3)

,District,Year,Crop,Season,Area,Production,Yield,Yield_Lag1,Yield_Lag2,Yield_3yr_Avg,...,june_percent_to_normal,july_normal_rainfall,july_actual_rainfall,july_percent_to_normal,august_normal_rainfall,august_actual_rainfall,august_percent_to_normal,september_normal_rainfall,september_actual_rainfall,september_percent_to_normal
0,ahilyanagar,1998,Arhar_Tur,Kharif,18800.0,9700.0,0.515957,0.357955,0.357955,0.515957,...,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
1,ahilyanagar,1998,Bajra,Kharif,302400.0,243900.0,0.806548,0.557461,0.557461,0.806548,...,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
2,ahilyanagar,1998,Castor_seed,Kharif,400.0,100.0,0.250000,0.250000,0.250000,0.250000,...,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3

In [74]:
import os

folder = "data"
filename = "final_merged_data_rain_plus_crop_yield.csv"
path = os.path.join(folder, filename)

# create folder if it doesn't exist
os.makedirs(folder, exist_ok=True)

if not os.path.exists(path):
    df.to_csv(path, index=False)
    print(f"File saved{path}")
else:
    print(f"File already exists at path: {path}, skipping...end")

File already exists at path: data/final_merged_data_rain_plus_crop_yield.csv, skipping...end