In [103]:
!uv pip freeze>requirements.txt

In [104]:
import pandas as pd

df = pd.read_csv("./data/final_merged_data_rain_plus_crop_yield.csv")

In [105]:
df.head(3)

,District,Year,Crop,Season,Area,Production,Yield,Yield_Lag1,Yield_Lag2,Yield_3yr_Avg,...,june_percent_to_normal,july_normal_rainfall,july_actual_rainfall,july_percent_to_normal,august_normal_rainfall,august_actual_rainfall,august_percent_to_normal,september_normal_rainfall,september_actual_rainfall,september_percent_to_normal
0,ahilyanagar,1998,Arhar_Tur,Kharif,18800.0,9700.0,0.515957,0.357955,0.357955,0.515957,...,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
1,ahilyanagar,1998,Bajra,Kharif,302400.0,243900.0,0.806548,0.557461,0.557461,0.806548,...,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
2,ahilyanagar,1998,Castor_seed,Kharif,400.0,100.0,0.250000,0.250000,0.250000,0.250000,...,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3

In [106]:
df.columns

Index(['District', 'Year', 'Crop', 'Season', 'Area', 'Production', 'Yield',
       'Yield_Lag1', 'Yield_Lag2', 'Yield_3yr_Avg', 'Yield_3yr_Std',
       'june_normal_rainfall', 'june_actual_rainfall',
       'june_percent_to_normal', 'july_normal_rainfall',
       'july_actual_rainfall', 'july_percent_to_normal',
       'august_normal_rainfall', 'august_actual_rainfall',
       'august_percent_to_normal', 'september_normal_rainfall',
       'september_actual_rainfall', 'september_percent_to_normal'],
      dtype='str')

In [107]:
X = df.drop(columns=[
    "Yield",
    "Production",
    "Area",
    "Crop",              # 🚨 REMOVE THIS
    "Yield_Lag1",
    "Yield_Lag2",
    "Yield_3yr_Avg",
    "Yield_3yr_Std"
], errors="ignore")
y = df["Yield"]

In [108]:
X.head(3)

,District,Year,Season,june_normal_rainfall,june_actual_rainfall,june_percent_to_normal,july_normal_rainfall,july_actual_rainfall,july_percent_to_normal,august_normal_rainfall,august_actual_rainfall,august_percent_to_normal,september_normal_rainfall,september_actual_rainfall,september_percent_to_normal
0,ahilyanagar,1998,Kharif,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
1,ahilyanagar,1998,Kharif,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
2,ahilyanagar,1998,Kharif,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3

In [109]:
X.head(3)

,District,Year,Season,june_normal_rainfall,june_actual_rainfall,june_percent_to_normal,july_normal_rainfall,july_actual_rainfall,july_percent_to_normal,august_normal_rainfall,august_actual_rainfall,august_percent_to_normal,september_normal_rainfall,september_actual_rainfall,september_percent_to_normal
0,ahilyanagar,1998,Kharif,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
1,ahilyanagar,1998,Kharif,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
2,ahilyanagar,1998,Kharif,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3

In [110]:
y.head(3)

0    0.515957
1    0.806548
2    0.250000
Name: Yield, dtype: float64

In [111]:
from sklearn.preprocessing import LabelEncoder

for col in ["Season", "District"]:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

In [112]:
X.head(10)

,District,Year,Season,june_normal_rainfall,june_actual_rainfall,june_percent_to_normal,july_normal_rainfall,july_actual_rainfall,july_percent_to_normal,august_normal_rainfall,august_actual_rainfall,august_percent_to_normal,september_normal_rainfall,september_actual_rainfall,september_percent_to_normal
0,0,1998,0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
1,0,1998,0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
2,0,1998,0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
3,0,1998,0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
4,0,1998,1,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
5,0,1998,0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
6,0,1998,2,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
7,0,1998,0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
8,0,1998,1,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
9,0,1998,1,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3

In [113]:
X.columns

Index(['District', 'Year', 'Season', 'june_normal_rainfall',
       'june_actual_rainfall', 'june_percent_to_normal',
       'july_normal_rainfall', 'july_actual_rainfall',
       'july_percent_to_normal', 'august_normal_rainfall',
       'august_actual_rainfall', 'august_percent_to_normal',
       'september_normal_rainfall', 'september_actual_rainfall',
       'september_percent_to_normal'],
      dtype='str')

In [114]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [115]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [116]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

preds = model.predict(X_test)

r2 = r2_score(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("R2:", r2)
print("RMSE:", rmse)

R2: -0.1177874594683177
RMSE: 3.7759906770812206

In [117]:
import pandas as pd

feat_imp = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feat_imp.head(10))

Season                       0.389040
june_percent_to_normal       0.087781
Year                         0.087103
august_percent_to_normal     0.070029
july_actual_rainfall         0.051713
july_percent_to_normal       0.044645
june_actual_rainfall         0.043452
august_actual_rainfall       0.038865
District                     0.036531
september_actual_rainfall    0.032520
dtype: float64

In [118]:
# WITH CROPS AND ALL THE LAG FEATURES

In [132]:
X = df.drop(columns=[
    "Yield",
    "Production",   # 🚨 remove
    "Area"          # 🚨 remove
])
y = df["Yield"]

In [133]:
from sklearn.preprocessing import LabelEncoder

for col in ["Crop", "Season", "District"]:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

In [134]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [135]:
X.head(5)

,District,Year,Crop,Season,Yield_Lag1,Yield_Lag2,Yield_3yr_Avg,Yield_3yr_Std,june_normal_rainfall,june_actual_rainfall,june_percent_to_normal,july_normal_rainfall,july_actual_rainfall,july_percent_to_normal,august_normal_rainfall,august_actual_rainfall,august_percent_to_normal,september_normal_rainfall,september_actual_rainfall,september_percent_to_normal
0,0,1998,0,0,0.357955,0.357955,0.515957,0.0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
1,0,1998,1,0,0.557461,0.557461,0.806548,0.0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
2,0,1998,2,0,0.250000,0.250000,0.250000,0.0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
3,0,1998,3,0,1.644628,1.644628,1.644628,0.0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3
4,0,1998,4,1,0.686242,0.686242,0.686242,0.0,108.2,137.0,126.6,97.5,133.5,136.9,95.4,178.1,186.7,147.0,191.6,130.3

In [136]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [137]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

preds = model.predict(X_test)

r2 = r2_score(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("R2:", r2)
print("RMSE:", rmse)

R2: 0.9876897627164072
RMSE: 0.39626389950724594

In [138]:
import pandas as pd

feat_imp = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feat_imp.head(10))

Yield_3yr_Avg             0.840534
Crop                      0.026356
Year                      0.023377
Yield_Lag1                0.017293
Yield_Lag2                0.016645
Yield_3yr_Std             0.015967
june_actual_rainfall      0.012160
august_actual_rainfall    0.010202
Season                    0.009609
june_percent_to_normal    0.005412
dtype: float64