In [2]:
!pip install pandas numpy scikit-learn openpyxl matplotlib seaborn xgboost lightgbm jupyter

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (2.3.1)
Requirement already satisfied: numpy in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (2.3.2)
Requirement already satisfied: scikit-learn in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (1.7.1)
Requirement already satisfied: openpyxl in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (3.10.5)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: jupyter in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (1.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: et-xmlfile in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from matplotlib) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: notebook in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter) (7.4.5)
Requirement already satisfied: jupyter-console in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter) (6.30.1)
Requirement already satisfied: ipywidgets in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter) (8.1.7)
Requirement already satisfied: jupyterlab in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter) (4.4.5)
Requirement already satisfied: six>=1.5 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (1.8.16)
Requirement already satisfied: ipython>=7.23.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (9.4.0)
Requirement already satisfied: jupyter-client>=8.0.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (0.1.7)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (7.0.0)
Requirement already satisfied: pyzmq>=25 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (27.0.1)
Requirement already satisfied: tornado>=6.2 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (6.5.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: colorama in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: stack_data in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.4)
Requirement already satisfied: platformdirs>=2.5 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (311)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipywidgets->jupyter) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from ipywidgets->jupyter) (3.0.15)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (2.2.6)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (2.16.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab->jupyter) (80.9.0)
Requirement already satisfied: anyio>=3.1.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.10.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.22.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.25.0)
Requirement already satisfied: requests>=2.31 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.32.3)
Requirement already satisfied: idna>=2.8 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.10)
Requirement already satisfied: sniffio>=1.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: argon2-cffi-bindings in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: certifi in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.27.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (24.11.1)
Requirement already satisfied: beautifulsoup4 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from nbconvert->jupyter) (4.13.4)
Requirement already satisfied: bleach!=5.0.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.2.0)
Requirement already satisfied: defusedxml in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from nbconvert->jupyter) (3.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: lark>=1.2.2 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.2.2)
Requirement already satisfied: cffi>=1.0.1 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.22)
Requirement already satisfied: soupsieve>1.2 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.14.1)
Requirement already satisfied: arrow>=0.15.0 in c:\users\adavith manoj\appdata\roaming\python\python313\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: C:\Python313\python.exe -m pip install --upgrade pip

In [4]:
%pip install pandas numpy scikit-learn openpyxl matplotlib seaborn xgboost

^C
Note: you may need to restart the kernel to use updated packages.

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting matplotlib
  Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adavith manoj\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\adavith manoj\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\adavith manoj\appdata\roaming\python\python312\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\adavith manoj\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (11.0.0)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\adavith manoj\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 4.8 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.7 MB 5.0 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.7 MB 4.9 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.7 MB 4.9 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.7 MB 4.9 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.7 MB 4.9 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.7 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.7 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 4.9 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 5.6 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.3 MB 5.1 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/12.3 MB 5.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.3 MB 5.1 MB/s eta 0:00:02
   ----------------- ---------------------- 5.2/12.3 MB 5.0 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.3 MB 4.9 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.3 MB 5.0 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 5.0 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 5.0 MB/s eta 0:00:01
   --------------------------------- ------ 10.2/12.3 MB 4.9 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 4.9 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.0 MB 5.6 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.0 MB 5.3 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.0 MB 5.6 MB/s eta 0:00:01
   ---------------------- ----------------- 4.5/8.0 MB 5.5 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.0 MB 5.4 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 5.3 MB/s eta 0:00:00
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.2 MB 5.6 MB/s eta 0:00:02
   ----------- ---------------------------- 2.4/8.2 MB 5.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.2 MB 5.1 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.2 MB 5.0 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.2 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.2 MB 5.2 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 5.2 MB/s eta 0:00:00
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ----------------- ---------------------- 1.0/2.3 MB 5.6 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 4.9 MB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   - -------------------------------------- 1.0/36.5 MB 5.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.4/36.5 MB 5.6 MB/s eta 0:00:07
   --- ------------------------------------ 3.4/36.5 MB 5.8 MB/s eta 0:00:06
   ----- ---------------------------------- 4.7/36.5 MB 5.7 MB/s eta 0:00:06
   ------ --------------------------------- 5.8/36.5 MB 5.7 MB/s eta 0:00:06
   ------- -------------------------------- 7.1/36.5 MB 5.7 MB/s eta 0:00:06
   -------- ------------------------------- 8.1/36.5 MB 5.7 MB/s eta 0:00:05
   ---------- ----------------------------- 9.4/36.5 MB 5.6 MB/s eta 0:00:05
   ----------- ---------------------------- 10.5/36.5 MB 5.6 MB/s eta 0:00:05
   ------------ --------------------------- 11.8/36.5 MB 5.6 MB/s eta 0:00:05
   -------------- ------------------------- 12.8/36.5 MB 5.6 MB/s eta 0:00:05
   --------------- ------------------------ 13.9/36.5 MB 5.6 MB/s eta 0:00:05
   ---------------- ----------------------- 15.2/36.5 MB 5.6 MB/s eta 0:00:04
   ----------------- ---------------------- 16.3/36.5 MB 5.6 MB/s eta 0:00:04
   ------------------- -------------------- 17.6/36.5 MB 5.6 MB/s eta 0:00:04
   -------------------- ------------------- 18.6/36.5 MB 5.5 MB/s eta 0:00:04
   --------------------- ------------------ 19.9/36.5 MB 5.5 MB/s eta 0:00:03
   ----------------------- ---------------- 21.2/36.5 MB 5.6 MB/s eta 0:00:03
   ------------------------ --------------- 22.3/36.5 MB 5.6 MB/s eta 0:00:03
   ------------------------- -------------- 23.6/36.5 MB 5.6 MB/s eta 0:00:03
   -------------------------- ------------- 24.6/36.5 MB 5.6 MB/s eta 0:00:03
   ---------------------------- ----------- 26.0/36.5 MB 5.6 MB/s eta 0:00:02
   ----------------------------- ---------- 27.3/36.5 MB 5.6 MB/s eta 0:00:02
   ------------------------------ --------- 28.3/36.5 MB 5.6 MB/s eta 0:00:02
   -------------------------------- ------- 29.6/36.5 MB 5.6 MB/s eta 0:00:02
   --------------------------------- ------ 30.9/36.5 MB 5.6 MB/s eta 0:00:01
   ----------------------------------- ---- 32.0/36.5 MB 5.6 MB/s eta 0:00:01
   ------------------------------------ --- 33.3/36.5 MB 5.7 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.5 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  35.7/36.5 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 5.6 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, pyparsing, numpy, kiwisolver, joblib, fonttools, et-xmlfile, cycler, scipy, pandas, openpyxl, contourpy, xgboost, scikit-learn, matplotlib, seaborn
Successfully installed contourpy-1.3.3 cycler-0.12.1 et-xmlfile-2.0.0 fonttools-4.62.1 joblib-1.5.3 kiwisolver-1.5.0 matplotlib-3.10.9 numpy-2.4.4 openpyxl-3.1.5 pandas-3.0.2 pyparsing-3.3.2 scikit-learn-1.8.0 scipy-1.17.1 seaborn-0.13.2 threadpoolctl-3.6.0 xgboost-3.2.0

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
%pip install lxml html5lib

Collecting lxml
  Downloading lxml-6.1.0-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\adavith manoj\appdata\roaming\python\python312\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading lxml-6.1.0-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 4.8 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/4.0 MB 4.6 MB/s eta 0:00:01
   ----------------------- ---------------- 2.4/4.0 MB 3.8 MB/s eta 0:00:01
   ---------------------------------- ----- 3.4/4.0 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 4.1 MB/s eta 0:00:00
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, lxml, html5lib
Successfully installed html5lib-1.1 lxml-6.1.0 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_list = pd.read_html("horizontal_crop_vertical_year_report_maharashtra.xls")
df = df_list[0]

df.head()

            State        District         Year      Arhar/Tur  \
            State        District         Year         Kharif
            State        District         Year Area (Hectare)
0  1. Maharashtra  1. Ahilyanagar  1997 - 1998        17600.0
1  1. Maharashtra  1. Ahilyanagar  1998 - 1999        18800.0
2  1. Maharashtra  1. Ahilyanagar  1999 - 2000        19000.0
3  1. Maharashtra  1. Ahilyanagar  2000 - 2001        19100.0
4  1. Maharashtra  1. Ahilyanagar  2001 - 2002        16700.0

                                                     Bajra  \
                                                    Kharif
  Production (Tonnes) Yield (Tonne/Hectare) Area (Hectare)
0              6300.0                  0.36       274100.0
1              9700.0                  0.52       302400.0
2              9900.0                  0.52       310600.0
3              9400.0                  0.49       326100.0
4              5400.0                  0.32       194400.0

                                                            ...  \
                                                    Summer  ...
  Production (Tonnes) Yield (Tonne/Hectare) Area (Hectare)  ...
0            152800.0                  0.56            NaN  ...
1            243900.0                  0.81            NaN  ...
2            178300.0                  0.57            NaN  ...
3            187300.0                  0.57            NaN  ...
4             82000.0                  0.42            NaN  ...

         other oilseeds                                     \
                 Kharif           Rabi
  Yield (Tonne/Hectare) Area (Hectare) Production (Tonnes)
0                   NaN            NaN                 NaN
1                   NaN            NaN                 NaN
2                   NaN            NaN                 NaN
3                   NaN            NaN                 NaN
4                   NaN            NaN                 NaN

                                                            \
                                Summer
  Yield (Tonne/Hectare) Area (Hectare) Production (Tonnes)
0                   NaN            NaN                 NaN
1                   NaN            NaN                 NaN
2                   NaN            NaN                 NaN
3                   NaN            NaN                 NaN
4                   NaN            NaN                 NaN

                        Other Summer Pulses                      \
                                     Summer
  Yield (Tonne/Hectare)      Area (Hectare) Production (Tonnes)
0                   NaN                 NaN                 NaN
1                   NaN                 NaN                 NaN
2                   NaN                 NaN                 NaN
3                   NaN                 NaN                 NaN
4                   NaN                 NaN                 NaN



  Yield (Tonne/Hectare)
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN

[5 rows x 156 columns]

In [4]:
df.columns.tolist()

[('State', 'State', 'State'),
 ('District', 'District', 'District'),
 ('Year', 'Year', 'Year'),
 ('Arhar/Tur', 'Kharif', 'Area (Hectare)'),
 ('Arhar/Tur', 'Kharif', 'Production (Tonnes)'),
 ('Arhar/Tur', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Bajra', 'Kharif', 'Area (Hectare)'),
 ('Bajra', 'Kharif', 'Production (Tonnes)'),
 ('Bajra', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Bajra', 'Summer', 'Area (Hectare)'),
 ('Bajra', 'Summer', 'Production (Tonnes)'),
 ('Bajra', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Gram', 'Kharif', 'Area (Hectare)'),
 ('Gram', 'Kharif', 'Production (Tonnes)'),
 ('Gram', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Gram', 'Rabi', 'Area (Hectare)'),
 ('Gram', 'Rabi', 'Production (Tonnes)'),
 ('Gram', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Jowar', 'Kharif', 'Area (Hectare)'),
 ('Jowar', 'Kharif', 'Production (Tonnes)'),
 ('Jowar', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Jowar', 'Rabi', 'Area (Hectare)'),
 ('Jowar', 'Rabi', 'Production (Tonnes)'),
 ('Jowar', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Jowar', 'Summer', 'Area (Hectare)'),
 ('Jowar', 'Summer', 'Production (Tonnes)'),
 ('Jowar', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Maize', 'Autumn', 'Area (Hectare)'),
 ('Maize', 'Autumn', 'Production (Tonnes)'),
 ('Maize', 'Autumn', 'Yield (Tonne/Hectare)'),
 ('Maize', 'Kharif', 'Area (Hectare)'),
 ('Maize', 'Kharif', 'Production (Tonnes)'),
 ('Maize', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Maize', 'Rabi', 'Area (Hectare)'),
 ('Maize', 'Rabi', 'Production (Tonnes)'),
 ('Maize', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Maize', 'Summer', 'Area (Hectare)'),
 ('Maize', 'Summer', 'Production (Tonnes)'),
 ('Maize', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Moong(Green Gram)', 'Kharif', 'Area (Hectare)'),
 ('Moong(Green Gram)', 'Kharif', 'Production (Tonnes)'),
 ('Moong(Green Gram)', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Moong(Green Gram)', 'Summer', 'Area (Hectare)'),
 ('Moong(Green Gram)', 'Summer', 'Production (Tonnes)'),
 ('Moong(Green Gram)', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Other Rabi pulses', 'Rabi', 'Area (Hectare)'),
 ('Other Rabi pulses', 'Rabi', 'Production (Tonnes)'),
 ('Other Rabi pulses', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Pulses total', 'Kharif', 'Area (Hectare)'),
 ('Pulses total', 'Kharif', 'Production (Tonnes)'),
 ('Pulses total', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Ragi', 'Kharif', 'Area (Hectare)'),
 ('Ragi', 'Kharif', 'Production (Tonnes)'),
 ('Ragi', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Rice', 'Kharif', 'Area (Hectare)'),
 ('Rice', 'Kharif', 'Production (Tonnes)'),
 ('Rice', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Rice', 'Summer', 'Area (Hectare)'),
 ('Rice', 'Summer', 'Production (Tonnes)'),
 ('Rice', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Sugarcane', 'Kharif', 'Area (Hectare)'),
 ('Sugarcane', 'Kharif', 'Production (Tonnes)'),
 ('Sugarcane', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Total foodgrain', 'Kharif', 'Area (Hectare)'),
 ('Total foodgrain', 'Kharif', 'Production (Tonnes)'),
 ('Total foodgrain', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Urad', 'Kharif', 'Area (Hectare)'),
 ('Urad', 'Kharif', 'Production (Tonnes)'),
 ('Urad', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Urad', 'Summer', 'Area (Hectare)'),
 ('Urad', 'Summer', 'Production (Tonnes)'),
 ('Urad', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Wheat', 'Rabi', 'Area (Hectare)'),
 ('Wheat', 'Rabi', 'Production (Tonnes)'),
 ('Wheat', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Castor seed', 'Kharif', 'Area (Hectare)'),
 ('Castor seed', 'Kharif', 'Production (Tonnes)'),
 ('Castor seed', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Cotton(lint)', 'Kharif', 'Area (Hectare)'),
 ('Cotton(lint)', 'Kharif', 'Production (Bales)'),
 ('Cotton(lint)', 'Kharif', 'Yield (Bales/Hectare)'),
 ('Groundnut', 'Kharif', 'Area (Hectare)'),
 ('Groundnut', 'Kharif', 'Production (Tonnes)'),
 ('Groundnut', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Groundnut', 'Summer', 'Area (Hectare)'),
 ('Groundnut', 'Summer', 'Production (Tonnes)'),
 ('Groundnut', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Linseed', 'Rabi', 'Area (Hectare)'),
 ('Linseed', 'Rabi', 'Production (Tonnes)'),
 ('Linseed', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Niger seed', 'Kharif', 'Area (Hectare)'),
 ('Niger seed', 'Kharif', 'Production (Tonnes)'),
 ('Niger seed', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Other Cereals', 'Kharif', 'Area (Hectare)'),
 ('Other Cereals', 'Kharif', 'Production (Tonnes)'),
 ('Other Cereals', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Other Cereals', 'Rabi', 'Area (Hectare)'),
 ('Other Cereals', 'Rabi', 'Production (Tonnes)'),
 ('Other Cereals', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Other Cereals', 'Summer', 'Area (Hectare)'),
 ('Other Cereals', 'Summer', 'Production (Tonnes)'),
 ('Other Cereals', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Other Kharif pulses', 'Kharif', 'Area (Hectare)'),
 ('Other Kharif pulses', 'Kharif', 'Production (Tonnes)'),
 ('Other Kharif pulses', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Rapeseed &Mustard', 'Rabi', 'Area (Hectare)'),
 ('Rapeseed &Mustard', 'Rabi', 'Production (Tonnes)'),
 ('Rapeseed &Mustard', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Safflower', 'Rabi', 'Area (Hectare)'),
 ('Safflower', 'Rabi', 'Production (Tonnes)'),
 ('Safflower', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Sesamum', 'Kharif', 'Area (Hectare)'),
 ('Sesamum', 'Kharif', 'Production (Tonnes)'),
 ('Sesamum', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Sesamum', 'Rabi', 'Area (Hectare)'),
 ('Sesamum', 'Rabi', 'Production (Tonnes)'),
 ('Sesamum', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Sesamum', 'Summer', 'Area (Hectare)'),
 ('Sesamum', 'Summer', 'Production (Tonnes)'),
 ('Sesamum', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Soyabean', 'Kharif', 'Area (Hectare)'),
 ('Soyabean', 'Kharif', 'Production (Tonnes)'),
 ('Soyabean', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Soyabean', 'Summer', 'Area (Hectare)'),
 ('Soyabean', 'Summer', 'Production (Tonnes)'),
 ('Soyabean', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Sunflower', 'Kharif', 'Area (Hectare)'),
 ('Sunflower', 'Kharif', 'Production (Tonnes)'),
 ('Sunflower', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Sunflower', 'Rabi', 'Area (Hectare)'),
 ('Sunflower', 'Rabi', 'Production (Tonnes)'),
 ('Sunflower', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Sunflower', 'Summer', 'Area (Hectare)'),
 ('Sunflower', 'Summer', 'Production (Tonnes)'),
 ('Sunflower', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Small millets', 'Kharif', 'Area (Hectare)'),
 ('Small millets', 'Kharif', 'Production (Tonnes)'),
 ('Small millets', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('Small millets', 'Rabi', 'Area (Hectare)'),
 ('Small millets', 'Rabi', 'Production (Tonnes)'),
 ('Small millets', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('Small millets', 'Summer', 'Area (Hectare)'),
 ('Small millets', 'Summer', 'Production (Tonnes)'),
 ('Small millets', 'Summer', 'Yield (Tonne/Hectare)'),
 ('other oilseeds', 'Kharif', 'Area (Hectare)'),
 ('other oilseeds', 'Kharif', 'Production (Tonnes)'),
 ('other oilseeds', 'Kharif', 'Yield (Tonne/Hectare)'),
 ('other oilseeds', 'Rabi', 'Area (Hectare)'),
 ('other oilseeds', 'Rabi', 'Production (Tonnes)'),
 ('other oilseeds', 'Rabi', 'Yield (Tonne/Hectare)'),
 ('other oilseeds', 'Summer', 'Area (Hectare)'),
 ('other oilseeds', 'Summer', 'Production (Tonnes)'),
 ('other oilseeds', 'Summer', 'Yield (Tonne/Hectare)'),
 ('Other Summer Pulses', 'Summer', 'Area (Hectare)'),
 ('Other Summer Pulses', 'Summer', 'Production (Tonnes)'),
 ('Other Summer Pulses', 'Summer', 'Yield (Tonne/Hectare)')]

In [5]:
df.columns = [
    f"{c1}_{c2}_{c3}" if c1 not in ['State', 'District', 'Year'] else c1
    for (c1, c2, c3) in df.columns
]

df.head()

,State,District,Year,Arhar/Tur_Kharif_Area (Hectare),Arhar/Tur_Kharif_Production (Tonnes),Arhar/Tur_Kharif_Yield (Tonne/Hectare),Bajra_Kharif_Area (Hectare),Bajra_Kharif_Production (Tonnes),Bajra_Kharif_Yield (Tonne/Hectare),Bajra_Summer_Area (Hectare),...,other oilseeds_Kharif_Yield (Tonne/Hectare),other oilseeds_Rabi_Area (Hectare),other oilseeds_Rabi_Production (Tonnes),other oilseeds_Rabi_Yield (Tonne/Hectare),other oilseeds_Summer_Area (Hectare),other oilseeds_Summer_Production (Tonnes),other oilseeds_Summer_Yield (Tonne/Hectare),Other Summer Pulses_Summer_Area (Hectare),Other Summer Pulses_Summer_Production (Tonnes),Other Summer Pulses_Summer_Yield (Tonne/Hectare)
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,17600.0,6300.0,0.36,274100.0,152800.0,0.56,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1. Maharashtra,1. Ahilyanagar,1998 - 1999,18800.0,9700.0,0.52,302400.0,243900.0,0.81,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1. Maharashtra,1. Ahilyanagar,1999 - 2000,19000.0,9900.0,0.52,310600.0,178300.0,0.57,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1. Maharashtra,1. Ahilyanagar,2000 - 2001,19100.0,9400.0,0.49,326100.0,187300.0,0.57,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1. Maharashtra,1. Ahilyanagar,2001 - 2002,16700.0,5400.0,0.32,194400.0,82000.0,0.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("/", "_")
df.columns = df.columns.str.replace("(", "")
df.columns = df.columns.str.replace(")", "")

df.columns.tolist()

['State',
 'District',
 'Year',
 'Arhar_Tur_Kharif_Area_Hectare',
 'Arhar_Tur_Kharif_Production_Tonnes',
 'Arhar_Tur_Kharif_Yield_Tonne_Hectare',
 'Bajra_Kharif_Area_Hectare',
 'Bajra_Kharif_Production_Tonnes',
 'Bajra_Kharif_Yield_Tonne_Hectare',
 'Bajra_Summer_Area_Hectare',
 'Bajra_Summer_Production_Tonnes',
 'Bajra_Summer_Yield_Tonne_Hectare',
 'Gram_Kharif_Area_Hectare',
 'Gram_Kharif_Production_Tonnes',
 'Gram_Kharif_Yield_Tonne_Hectare',
 'Gram_Rabi_Area_Hectare',
 'Gram_Rabi_Production_Tonnes',
 'Gram_Rabi_Yield_Tonne_Hectare',
 'Jowar_Kharif_Area_Hectare',
 'Jowar_Kharif_Production_Tonnes',
 'Jowar_Kharif_Yield_Tonne_Hectare',
 'Jowar_Rabi_Area_Hectare',
 'Jowar_Rabi_Production_Tonnes',
 'Jowar_Rabi_Yield_Tonne_Hectare',
 'Jowar_Summer_Area_Hectare',
 'Jowar_Summer_Production_Tonnes',
 'Jowar_Summer_Yield_Tonne_Hectare',
 'Maize_Autumn_Area_Hectare',
 'Maize_Autumn_Production_Tonnes',
 'Maize_Autumn_Yield_Tonne_Hectare',
 'Maize_Kharif_Area_Hectare',
 'Maize_Kharif_Production_Tonnes',
 'Maize_Kharif_Yield_Tonne_Hectare',
 'Maize_Rabi_Area_Hectare',
 'Maize_Rabi_Production_Tonnes',
 'Maize_Rabi_Yield_Tonne_Hectare',
 'Maize_Summer_Area_Hectare',
 'Maize_Summer_Production_Tonnes',
 'Maize_Summer_Yield_Tonne_Hectare',
 'MoongGreen_Gram_Kharif_Area_Hectare',
 'MoongGreen_Gram_Kharif_Production_Tonnes',
 'MoongGreen_Gram_Kharif_Yield_Tonne_Hectare',
 'MoongGreen_Gram_Summer_Area_Hectare',
 'MoongGreen_Gram_Summer_Production_Tonnes',
 'MoongGreen_Gram_Summer_Yield_Tonne_Hectare',
 'Other_Rabi_pulses_Rabi_Area_Hectare',
 'Other_Rabi_pulses_Rabi_Production_Tonnes',
 'Other_Rabi_pulses_Rabi_Yield_Tonne_Hectare',
 'Pulses_total_Kharif_Area_Hectare',
 'Pulses_total_Kharif_Production_Tonnes',
 'Pulses_total_Kharif_Yield_Tonne_Hectare',
 'Ragi_Kharif_Area_Hectare',
 'Ragi_Kharif_Production_Tonnes',
 'Ragi_Kharif_Yield_Tonne_Hectare',
 'Rice_Kharif_Area_Hectare',
 'Rice_Kharif_Production_Tonnes',
 'Rice_Kharif_Yield_Tonne_Hectare',
 'Rice_Summer_Area_Hectare',
 'Rice_Summer_Production_Tonnes',
 'Rice_Summer_Yield_Tonne_Hectare',
 'Sugarcane_Kharif_Area_Hectare',
 'Sugarcane_Kharif_Production_Tonnes',
 'Sugarcane_Kharif_Yield_Tonne_Hectare',
 'Total_foodgrain_Kharif_Area_Hectare',
 'Total_foodgrain_Kharif_Production_Tonnes',
 'Total_foodgrain_Kharif_Yield_Tonne_Hectare',
 'Urad_Kharif_Area_Hectare',
 'Urad_Kharif_Production_Tonnes',
 'Urad_Kharif_Yield_Tonne_Hectare',
 'Urad_Summer_Area_Hectare',
 'Urad_Summer_Production_Tonnes',
 'Urad_Summer_Yield_Tonne_Hectare',
 'Wheat_Rabi_Area_Hectare',
 'Wheat_Rabi_Production_Tonnes',
 'Wheat_Rabi_Yield_Tonne_Hectare',
 'Castor_seed_Kharif_Area_Hectare',
 'Castor_seed_Kharif_Production_Tonnes',
 'Castor_seed_Kharif_Yield_Tonne_Hectare',
 'Cottonlint_Kharif_Area_Hectare',
 'Cottonlint_Kharif_Production_Bales',
 'Cottonlint_Kharif_Yield_Bales_Hectare',
 'Groundnut_Kharif_Area_Hectare',
 'Groundnut_Kharif_Production_Tonnes',
 'Groundnut_Kharif_Yield_Tonne_Hectare',
 'Groundnut_Summer_Area_Hectare',
 'Groundnut_Summer_Production_Tonnes',
 'Groundnut_Summer_Yield_Tonne_Hectare',
 'Linseed_Rabi_Area_Hectare',
 'Linseed_Rabi_Production_Tonnes',
 'Linseed_Rabi_Yield_Tonne_Hectare',
 'Niger_seed_Kharif_Area_Hectare',
 'Niger_seed_Kharif_Production_Tonnes',
 'Niger_seed_Kharif_Yield_Tonne_Hectare',
 'Other_Cereals_Kharif_Area_Hectare',
 'Other_Cereals_Kharif_Production_Tonnes',
 'Other_Cereals_Kharif_Yield_Tonne_Hectare',
 'Other_Cereals_Rabi_Area_Hectare',
 'Other_Cereals_Rabi_Production_Tonnes',
 'Other_Cereals_Rabi_Yield_Tonne_Hectare',
 'Other_Cereals_Summer_Area_Hectare',
 'Other_Cereals_Summer_Production_Tonnes',
 'Other_Cereals_Summer_Yield_Tonne_Hectare',
 'Other_Kharif_pulses_Kharif_Area_Hectare',
 'Other_Kharif_pulses_Kharif_Production_Tonnes',
 'Other_Kharif_pulses_Kharif_Yield_Tonne_Hectare',
 'Rapeseed_&Mustard_Rabi_Area_Hectare',
 'Rapeseed_&Mustard_Rabi_Production_Tonnes',
 'Rapeseed_&Mustard_Rabi_Yield_Tonne_Hectare',
 'Safflower_Rabi_Area_Hectare',
 'Safflower_Rabi_Production_Tonnes',
 'Safflower_Rabi_Yield_Tonne_Hectare',
 'Sesamum_Kharif_Area_Hectare',
 'Sesamum_Kharif_Production_Tonnes',
 'Sesamum_Kharif_Yield_Tonne_Hectare',
 'Sesamum_Rabi_Area_Hectare',
 'Sesamum_Rabi_Production_Tonnes',
 'Sesamum_Rabi_Yield_Tonne_Hectare',
 'Sesamum_Summer_Area_Hectare',
 'Sesamum_Summer_Production_Tonnes',
 'Sesamum_Summer_Yield_Tonne_Hectare',
 'Soyabean_Kharif_Area_Hectare',
 'Soyabean_Kharif_Production_Tonnes',
 'Soyabean_Kharif_Yield_Tonne_Hectare',
 'Soyabean_Summer_Area_Hectare',
 'Soyabean_Summer_Production_Tonnes',
 'Soyabean_Summer_Yield_Tonne_Hectare',
 'Sunflower_Kharif_Area_Hectare',
 'Sunflower_Kharif_Production_Tonnes',
 'Sunflower_Kharif_Yield_Tonne_Hectare',
 'Sunflower_Rabi_Area_Hectare',
 'Sunflower_Rabi_Production_Tonnes',
 'Sunflower_Rabi_Yield_Tonne_Hectare',
 'Sunflower_Summer_Area_Hectare',
 'Sunflower_Summer_Production_Tonnes',
 'Sunflower_Summer_Yield_Tonne_Hectare',
 'Small_millets_Kharif_Area_Hectare',
 'Small_millets_Kharif_Production_Tonnes',
 'Small_millets_Kharif_Yield_Tonne_Hectare',
 'Small_millets_Rabi_Area_Hectare',
 'Small_millets_Rabi_Production_Tonnes',
 'Small_millets_Rabi_Yield_Tonne_Hectare',
 'Small_millets_Summer_Area_Hectare',
 'Small_millets_Summer_Production_Tonnes',
 'Small_millets_Summer_Yield_Tonne_Hectare',
 'other_oilseeds_Kharif_Area_Hectare',
 'other_oilseeds_Kharif_Production_Tonnes',
 'other_oilseeds_Kharif_Yield_Tonne_Hectare',
 'other_oilseeds_Rabi_Area_Hectare',
 'other_oilseeds_Rabi_Production_Tonnes',
 'other_oilseeds_Rabi_Yield_Tonne_Hectare',
 'other_oilseeds_Summer_Area_Hectare',
 'other_oilseeds_Summer_Production_Tonnes',
 'other_oilseeds_Summer_Yield_Tonne_Hectare',
 'Other_Summer_Pulses_Summer_Area_Hectare',
 'Other_Summer_Pulses_Summer_Production_Tonnes',
 'Other_Summer_Pulses_Summer_Yield_Tonne_Hectare']

In [7]:
cols = [col for col in df.columns if col not in ['State', 'District', 'Year']]

In [8]:
rows = []

for col in cols:
    parts = col.split("_")
    
    # Extract components
    crop = parts[0]
    if len(parts) > 3:
        crop = "_".join(parts[:-3])  # handles names like "Other_Summer_Pulses"
    
    season = parts[-3]
    metric = parts[-2]  # Area / Production / Yield
    
    for i in range(len(df)):
        rows.append({
            'State': df.loc[i, 'State'],
            'District': df.loc[i, 'District'],
            'Year': df.loc[i, 'Year'],
            'Crop': crop,
            'Season': season,
            'Metric': metric,
            'Value': df.loc[i, col]
        })

long_df = pd.DataFrame(rows)
long_df.head()

,State,District,Year,Crop,Season,Metric,Value
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Arhar_Tur,Kharif,Area,17600.0
1,1. Maharashtra,1. Ahilyanagar,1998 - 1999,Arhar_Tur,Kharif,Area,18800.0
2,1. Maharashtra,1. Ahilyanagar,1999 - 2000,Arhar_Tur,Kharif,Area,19000.0
3,1. Maharashtra,1. Ahilyanagar,2000 - 2001,Arhar_Tur,Kharif,Area,19100.0
4,1. Maharashtra,1. Ahilyanagar,2001 - 2002,Arhar_Tur,Kharif,Area,16700.0

In [9]:
master_df = long_df.pivot_table(
    index=['State', 'District', 'Year', 'Crop', 'Season'],
    columns='Metric',
    values='Value'
).reset_index()

master_df.head()

Metric,State,District,Year,Crop,Season,Area,Bales,Production,Tonne
0,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Arhar_Tur,Kharif,17600.0,NaN,6300.0,NaN
1,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Arhar_Tur_Kharif,Yield,NaN,NaN,NaN,0.36
2,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Bajra,Kharif,274100.0,NaN,152800.0,NaN
3,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Bajra_Kharif,Yield,NaN,NaN,NaN,0.56
4,1. Maharashtra,1. Ahilyanagar,1997 - 1998,Gram,Kharif,40800.0,NaN,18600.0,NaN

In [10]:
master_df.columns.name = None

master_df = master_df.rename(columns={
    'Area': 'Area',
    'Production': 'Production',
    'Yield': 'Yield'
})

In [11]:
master_df['Year'] = master_df['Year'].astype(str).str[:4].astype(int)

In [14]:
master_df['Yield'] = master_df['Production'] / master_df['Area']

In [16]:
master_df.head()

,State,District,Year,Crop,Season,Area,Bales,Production,Tonne,Yield
0,1. Maharashtra,1. Ahilyanagar,1997,Arhar_Tur,Kharif,17600.0,NaN,6300.0,NaN,0.357955
1,1. Maharashtra,1. Ahilyanagar,1997,Arhar_Tur_Kharif,Yield,NaN,NaN,NaN,0.36,NaN
2,1. Maharashtra,1. Ahilyanagar,1997,Bajra,Kharif,274100.0,NaN,152800.0,NaN,0.557461
3,1. Maharashtra,1. Ahilyanagar,1997,Bajra_Kharif,Yield,NaN,NaN,NaN,0.56,NaN
4,1. Maharashtra,1. Ahilyanagar,1997,Gram,Kharif,40800.0,NaN,18600.0,NaN,0.455882

In [17]:
master_df = master_df.replace([np.inf, -np.inf], np.nan)
master_df = master_df.dropna(subset=['Yield'])
master_df = master_df[master_df['Area'] > 0]

In [19]:
master_df = master_df.drop(columns=['State','Bales', 'Tonne'], errors='ignore')

In [22]:
master_df.head()
master_df.columns

Index(['District', 'Year', 'Crop', 'Season', 'Area', 'Production', 'Yield'], dtype='str')

In [24]:
master_df.groupby('District')['Year'].agg(['min', 'max', 'nunique'])

                               min   max  nunique
District
1. Ahilyanagar                1997  2022       26
10. Dhule                     1997  2022       26
11. Gadchiroli                1997  2022       26
12. Gondia                    1999  2022       24
13. Hingoli                   1999  2022       24
14. Jalgaon                   1997  2022       26
15. Jalna                     1997  2022       26
16. Kolhapur                  1997  2022       26
17. Latur                     1997  2022       26
18. Mumbai                    1997  1997        1
19. Mumbai suburban           2016  2019        2
2. Akola                      1997  2022       26
20. Nagpur                    1997  2022       26
21. Nanded                    1997  2022       26
22. Nandurbar                 1999  2022       24
23. Nashik                    1997  2022       26
24. Palghar                   2005  2022       11
25. Parbhani                  1997  2022       26
26. Pune                      1997  2022       26
27. Raigad                    1997  2022       26
28. Ratnagiri                 1997  2022       26
29. Sangli                    1997  2022       26
3. Amravati                   1997  2022       26
30. Satara                    1997  2022       26
31. Sindhudurg                1997  2022       26
32. Solapur                   1997  2022       26
33. Thane                     1997  2022       26
34. Wardha                    1997  2022       26
35. Washim                    1999  2022       24
36. Yavatmal                  1997  2022       26
4. Beed                       1997  2022       26
5. Bhandara                   1997  2022       26
6. Buldhana                   1997  2022       26
7. Chandrapur                 1997  2022       26
8. Chhatrapati Sambhajinagar  1997  2022       26
9. Dharashiv                  1997  2022       26

In [25]:
master_df = master_df.sort_values(['District', 'Crop', 'Season', 'Year'])

In [26]:
master_df['Yield_Lag1'] = (
    master_df.groupby(['District', 'Crop', 'Season'])['Yield']
    .shift(1)
)

In [30]:
master_df['Yield_Lag2'] = master_df.groupby(['District','Crop','Season'])['Yield'].shift(2)

In [28]:
master_df['Yield_3yr_Avg'] = (
    master_df.groupby(['District', 'Crop', 'Season'])['Yield']
    .transform(lambda x: x.rolling(3).mean())
)

In [29]:
master_df['Yield_3yr_Std'] = (
    master_df.groupby(['District', 'Crop', 'Season'])['Yield']
    .transform(lambda x: x.rolling(3).std())
)

In [31]:
master_df.head()

,District,Year,Crop,Season,Area,Production,Yield,Yield_Lag1,Yield_3yr_Avg,Yield_3yr_Std,Yield_Lag2
0,1. Ahilyanagar,1997,Arhar_Tur,Kharif,17600.0,6300.0,0.357955,NaN,NaN,NaN,NaN
36,1. Ahilyanagar,1998,Arhar_Tur,Kharif,18800.0,9700.0,0.515957,0.357955,NaN,NaN,NaN
100,1. Ahilyanagar,1999,Arhar_Tur,Kharif,19000.0,9900.0,0.521053,0.515957,0.464988,0.092729,0.357955
162,1. Ahilyanagar,2000,Arhar_Tur,Kharif,19100.0,9400.0,0.492147,0.521053,0.509719,0.015430,0.515957
220,1. Ahilyanagar,2001,Arhar_Tur,Kharif,16700.0,5400.0,0.323353,0.492147,0.445518,0.106780,0.521053

In [32]:
# Keep lag1 but fill missing with current yield
master_df['Yield_Lag1'] = master_df['Yield_Lag1'].fillna(master_df['Yield'])

In [33]:
master_df['Yield_Lag2'] = master_df['Yield_Lag2'].fillna(master_df['Yield_Lag1'])

In [34]:
master_df['Yield_3yr_Avg'] = master_df['Yield_3yr_Avg'].fillna(master_df['Yield'])

In [35]:
master_df['Yield_3yr_Std'] = master_df['Yield_3yr_Std'].fillna(0)

In [36]:
master_df.isna().sum()

District         0
Year             0
Crop             0
Season           0
Area             0
Production       0
Yield            0
Yield_Lag1       0
Yield_3yr_Avg    0
Yield_3yr_Std    0
Yield_Lag2       0
dtype: int64

In [37]:
cols = [
    'District', 'Year', 'Crop', 'Season',
    'Area', 'Production','Yield',
    'Yield_Lag1', 'Yield_Lag2',
    'Yield_3yr_Avg', 'Yield_3yr_Std'
]

master_df = master_df[cols]

In [38]:
master_df.head()

,District,Year,Crop,Season,Area,Production,Yield,Yield_Lag1,Yield_Lag2,Yield_3yr_Avg,Yield_3yr_Std
0,1. Ahilyanagar,1997,Arhar_Tur,Kharif,17600.0,6300.0,0.357955,0.357955,0.357955,0.357955,0.000000
36,1. Ahilyanagar,1998,Arhar_Tur,Kharif,18800.0,9700.0,0.515957,0.357955,0.357955,0.515957,0.000000
100,1. Ahilyanagar,1999,Arhar_Tur,Kharif,19000.0,9900.0,0.521053,0.515957,0.357955,0.464988,0.092729
162,1. Ahilyanagar,2000,Arhar_Tur,Kharif,19100.0,9400.0,0.492147,0.521053,0.515957,0.509719,0.015430
220,1. Ahilyanagar,2001,Arhar_Tur,Kharif,16700.0,5400.0,0.323353,0.492147,0.521053,0.445518,0.106780

In [41]:
master_df['District'].unique()

<StringArray>
[              '1. Ahilyanagar',                    '10. Dhule',
               '11. Gadchiroli',                   '12. Gondia',
                  '13. Hingoli',                  '14. Jalgaon',
                    '15. Jalna',                 '16. Kolhapur',
                    '17. Latur',                   '18. Mumbai',
          '19. Mumbai suburban',                     '2. Akola',
                   '20. Nagpur',                   '21. Nanded',
                '22. Nandurbar',                   '23. Nashik',
                  '24. Palghar',                 '25. Parbhani',
                     '26. Pune',                   '27. Raigad',
                '28. Ratnagiri',                   '29. Sangli',
                  '3. Amravati',                   '30. Satara',
               '31. Sindhudurg',                  '32. Solapur',
                    '33. Thane',                   '34. Wardha',
                   '35. Washim',                 '36. Yavatmal',
                      '4. Beed',                  '5. Bhandara',
                  '6. Buldhana',                '7. Chandrapur',
 '8. Chhatrapati Sambhajinagar',                 '9. Dharashiv']
Length: 36, dtype: str

In [42]:
master_df['District_Num'] = master_df['District'].str.extract(r'(\d+)').astype(int)

In [43]:
master_df['District_Name'] = master_df['District'].str.replace(r'^\d+\.\s*', '', regex=True)

In [44]:
master_df = master_df.sort_values(['District_Num', 'Year'])

In [45]:
master_df['District'] = master_df['District_Name']
master_df = master_df.drop(columns=['District_Name', 'District_Num'])

In [46]:
master_df.to_csv("master_crop_data_clean.csv", index=False)